<?xml version="1.0" ?>
<!DOCTYPE _rct_preparacion [
  <!ELEMENT _rct_preparacion (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (id_receta?,orden?,descripcion?,id?,descripcion_v?,trial448?)+>
  <!ELEMENT id_receta (#PCDATA)>
  <!ELEMENT orden (#PCDATA)>
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT descripcion_v (#PCDATA)>
  <!ELEMENT trial448 (#PCDATA)>
]>
<_rct_preparacion>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>1</orden>
    <descripcion>Cocer los garbanzos en una cazuela con agua caliente (si son garbanzos secos hay que dejarlos a remojo la noche anterior).</descripcion>
    <id>23.770</id>
    <descripcion_v>Coeu els cigrons en una cassola amb aigua calenta (si són cigrons secs cal deixar-los en remull la nit anterior).</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>2</orden>
    <descripcion>Cocer las espinacas en agua hirviendo con sal.</descripcion>
    <id>23.771</id>
    <descripcion_v>Coeu els espinacs en aigua bullint amb sal.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>3</orden>
    <descripcion>Freír la cebolla con un poco de aceite. Cuando esté dorada, añadir las espinacas.</descripcion>
    <id>23.772</id>
    <descripcion_v>Fregiu la ceba amb un poc d'oli. Quan estiga daurada, afegiu-hi els espinacs.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>4</orden>
    <descripcion>Incorporar a los garbanzos cuando estén cocidos.</descripcion>
    <id>23.773</id>
    <descripcion_v>Incorporeu-los als cigrons quan estiguen cuits.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>5</orden>
    <descripcion>Hervir el huevo.</descripcion>
    <id>23.774</id>
    <descripcion_v>Bulliu l'ou.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>6</orden>
    <descripcion>Freír los ajos en una sartén y retirar. En el mismo aceite freír el pan y retirar.</descripcion>
    <id>23.775</id>
    <descripcion_v>Fregiu els alls en una paella i retireu-los. En el mateix oli fregiu el pa i retireu-lo.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>7</orden>
    <descripcion>Mezclar en un mortero, con la yema de huevo y el perejil.</descripcion>
    <id>23.776</id>
    <descripcion_v>Mescleu-ho en un morter amb el rovell d'ou i el julivert.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>8</orden>
    <descripcion>Añadir la mezcla del mortero a los garbanzos y cocer unos minutos más.</descripcion>
    <id>23.777</id>
    <descripcion_v>Afegiu-hi la mescla del morter als cigrons i coeu-ho uns minuts més.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>0</id_receta>
    <orden>9</orden>
    <descripcion>Para servir, añadir la clara de huevo picada, por encima.</descripcion>
    <id>23.778</id>
    <descripcion_v>Per a servir, afegiu-hi la clara d'ou picada per damunt.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>709</id_receta>
    <orden>1</orden>
    <descripcion>Pon a calentar 3 vasos de agua en una olla, con el laurel, media cebolla, un diente de ajo partido en dos y medio tomate. Déjala hervir lentamente durante 5 minutos. Añade las alubias, déjalas hervir un par de minutos y apaga el fuego. Deja macerar las alubias mientras preparas el resto de la receta. En una sartén, con 2 cucharadas de aceite, pon los calamares cortados en anillas, sin sazonar, y muy bien escurridos. Tapa la sartén  y deja que se hagan lentamente. Remuévelos de vez en cuando. Cuando comiencen a absorber de nuevo el líquido que habrán soltado, sazónalo y añade el perejil y un diente de ajo picados. Por último, agrega el vino y deja reducir.</descripcion>
    <id>26.582</id>
    <descripcion_v>Posa a calfar 3 gots d’aigua en una olla, amb el llorer, mitja ceba, un all partit en dos i mitja tomaca. Deixa-la bullir lentament durant 5 minuts. Afig els fesols, deixa-les bullir un parell de minuts i apaga el foc. Deixa macerar els fesols mentres prepares la resta de la recepta . En una paella, amb 2 cullerades d’oli, posa els calamars tallats en anelles, sense salar, i molt ben escorreguts. Tapa la paella  i deixa que es facen lentament. Remena'ls de tant en tant. Quan comencen a absorbir novament el líquid que hauran tret, sala'ls i afig-hi el julivert i un all picats. Finalment, tira-hi el vi i deixa-ho reduir.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>709</id_receta>
    <orden>2</orden>
    <descripcion>Mientras tanto, en una cazuela plana, prepara un sofrito con el resto del aceite. Primero la cebolla picada fina, después los ajos restantes y el pimiento, y finalmente el resto del tomate. Sazona</descripcion>
    <id>26.583</id>
    <descripcion_v>Mentrestant, en una cassola plana, prepara un sofregit amb la resta de l’oli. De primer la ceba picada fina, després els restants alls i el pimentó, i finalment la resta de la tomaca. Sala-ho.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>709</id_receta>
    <orden>3</orden>
    <descripcion>Agrega a la cazuela los calamares con su jugo y mezcla bien. Deja cocer durante 5 minutos, removiendo de vez en cuando. Finalmente, añade las alubias escurridas y deja cocer a fuego bajo hasta 10 minutos más, añadiendo poco a poco caldo de las alubias, para que todos los ingredientes queden bien ligados.</descripcion>
    <id>26.584</id>
    <descripcion_v>Agrega a la cassola els calamars amb el suc i mescla-ho bé. Deixa-ho coure durant 5 minuts, remenant de tant en tant. Finalment, afig-hi els fesols escorreguts i deixa-ho coure a foc baix fins 10 minuts més, afegint a poc a poc caldo dels fesols, perquè tots els ingredients queden ben lligats.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>707</id_receta>
    <orden>1</orden>
    <descripcion>Coloca las lentejas en una cazuela baja, con 2 cucharadas de aceite y un pellizco de sal, cúbrelas con agua y caliéntalas a fuego bajo, sin que apenas lleguen a hervir.</descripcion>
    <id>26.797</id>
    <descripcion_v>Col•loca les llentilles en una cassola baixa, amb 2 cullerades d’oli i un pessic de sal, cobrix-les amb aigua i calfa-les a foc baix, sense que a penes arriben a bullir.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>707</id_receta>
    <orden>2</orden>
    <descripcion>Pica muy pequeños los ajos, las cebollas y los pimientos, y ponlos a pochar a fuego bajo en una sartén con un poco de aceite de oliva. Corta los chipirones a trozos medianos, de un par de centímetros.</descripcion>
    <id>26.798</id>
    <descripcion_v>Pica molt menuts els alls, les cebes i els pimentons, i posa’ls a ofegar a foc baix en una paella amb un poc d’oli d’oliva. Talla els calamarsons en trossos mitjans, d’un parell de centímetres.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>707</id_receta>
    <orden>3</orden>
    <descripcion>Cuando las verduras estén medio hechas, al cabo de unos 8 minutos, agrega los chipirones y deja cocer, siempre a fuego bajo, hasta que vuelvan a absorber el líquido que habrán soltado. Sazona un poco y deja cocer un par de minutos.</descripcion>
    <id>26.799</id>
    <descripcion_v>Quan les verdures estiguen mig fetes, al cap d’uns 8 minuts, tira-hi els calamarsons i deixa'ls coure, sempre a foc baix, fins que tornen a absorbir el líquid que hauran tret. Sala'ls un poc i deixa'ls coure un parell de minuts.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>707</id_receta>
    <orden>4</orden>
    <descripcion>Agrega todo el contenido de la sartén a la cazuela de las lentejas, mezcla bien con una cuchara de madera, agrega el pimentón y deja cocer a fuego muy bajo durante 10 minutos más, con la cazuela destapada.</descripcion>
    <id>26.800</id>
    <descripcion_v>Agrega tot el contingut de la paella a la cassola de les llentilles, mescla-ho bé amb una cullera de fusta, agrega-hi el pebre roig i deixa-ho coure a foc molt baix durant 10 minuts més, amb la cassola destapada.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>707</id_receta>
    <orden>5</orden>
    <descripcion>Si lo consideras necesario añade un poco más de agua, ya que deben quedar un poco caldosas. Se sirven calientes, con un poco de perejil picado por encima.</descripcion>
    <id>26.801</id>
    <descripcion_v>Si ho consideres necessari, afig-hi un poc més d’aigua, ja que han de quedar un poc caldoses. Se servixen calentes, amb un poc de julivert picat per damunt.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>887</id_receta>
    <orden>1</orden>
    <descripcion>Prepara el té con ½ litro de agua  hervida y la cáscara de la naranja. Deja reposar durante 5 minutos y cuela. Ralla la cáscara de 1 limón y reserva la cáscara de otro. Exprime la naranja y los 3 limones.</descripcion>
    <id>28.204</id>
    <descripcion_v>Prepara el te amb ½ litre d’aigua bullida i la corfa de la taronja. Deixa’l reposar durant 5 minuts i cola’l. Ratlla la corfa d’1 llima i reserva la corfa d’una altra. Escorre la taronja i les 3 llimes.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>887</id_receta>
    <orden>2</orden>
    <descripcion>Coloca en una jarra los zumos, el té y mezcla bien con la miel y los granos de polen con ayuda de una cuchara de madera.</descripcion>
    <id>28.205</id>
    <descripcion_v>Col·loca els sucs i el te en un pitxer i mescla-ho bé amb la mel i els grans de pol·len amb ajuda d’una cullera de fusta.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>887</id_receta>
    <orden>3</orden>
    <descripcion>Incorpora la ralladura, la cáscara del otro limón, la hierbabuena y los hielos. Cubre con el agua con gas y sirve en copas.</descripcion>
    <id>28.206</id>
    <descripcion_v>Incorpora-hi la ratlladura, la corfa de l’altre llima, l’herba-sana i els glaçons. Cobrix-ho amb l’aigua amb gas i servix-ho en copes.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>7</id_receta>
    <orden>1</orden>
    <descripcion>Triturar las almendras y el diente de ajo hasta conseguir una pasta fina. Añadir un poco de sal.</descripcion>
    <id>30.994</id>
    <descripcion_v>Tritureu les ametles i l'all fins a aconseguir una pasta fina. Afegiu-hi un poc de sal.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>7</id_receta>
    <orden>2</orden>
    <descripcion>Incorporar la miga de pan (mojar previamente en agua y unas cucharaditas de vinagre)</descripcion>
    <id>30.995</id>
    <descripcion_v>Incorporeu-hi la molla de pa (mulleu-la prèviament en aigua i unes culleradetes de vinagre).</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>7</id_receta>
    <orden>3</orden>
    <descripcion>Batir.</descripcion>
    <id>30.996</id>
    <descripcion_v>Bateu-ho.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>7</id_receta>
    <orden>4</orden>
    <descripcion>Incorporar el aceite poco a poco y a continuación el agua.</descripcion>
    <id>30.997</id>
    <descripcion_v>Incorporeu-hi l'oli a poc a poc i a continuació l'aigua.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>7</id_receta>
    <orden>5</orden>
    <descripcion>Servir muy frío.</descripcion>
    <id>30.998</id>
    <descripcion_v>Serviu-ho molt fred.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>497</id_receta>
    <orden>1</orden>
    <descripcion>Lavar y triturar los champiñones crudos. Reservar</descripcion>
    <id>31.026</id>
    <descripcion_v>Llaveu els xampinyons crus, tritureu-los i reserveu-los.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>497</id_receta>
    <orden>2</orden>
    <descripcion>Picar la cebolla y el ajo. Sofreír en una sartén con abundante aceite y dejar que se doren. Añadir los champiñones triturados. Dejar a fuego medio unas 20 minutos o hasta que se evapore el agua.</descripcion>
    <id>31.027</id>
    <descripcion_v>Piqueu la ceba i l'all. Sofregiu-los en una paella amb oli abundant i deixeu que es dauren. Afegiu-hi els xampinyons triturats. Deixeu-ho a foc mitjà uns 20 minuts o fins que s'evapore l'aigua.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>497</id_receta>
    <orden>3</orden>
    <descripcion>En un recipiente hondo mezclar el sofrito con el huevo, el pan rallado y el perejil picado. Mezclar bien y dar forma a las albóndigas.</descripcion>
    <id>31.028</id>
    <descripcion_v>En un recipient fondo barregeu el sofregit amb l'ou, el pa ratllat i el julivert picat. Mescleu-ho bé i doneu forma a les mandonguilles.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>497</id_receta>
    <orden>4</orden>
    <descripcion>Pasarlas por pan rallado y freírlas en abundante aceite caliente.</descripcion>
    <id>31.029</id>
    <descripcion_v>Passeu-les per pa ratllat i fregiu-les en oli calent abundant.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>497</id_receta>
    <orden>5</orden>
    <descripcion>Pelar y trocear la calabaza. Poner en una cazuela cubierta de agua. Cocer unos 15 - 20 minutos. Triturar y salpimentar en la misma cazuela. Incorporar los guisantes y cocer unos 10 minutos más.</descripcion>
    <id>31.030</id>
    <descripcion_v>Peleu la carabassa i trossegeu-la. Poseu-la en una cassola coberta d'aigua. Coeu-la uns 15 - 20 minuts. Tritureu-la i salpebreu-la en la mateixa cassola. Incorporeu-hi els pésols i coeu-ho uns 10 minuts més.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>497</id_receta>
    <orden>6</orden>
    <descripcion>Servir en un plato hondo las albóndigas acompañadas de la crema de calabaza.</descripcion>
    <id>31.031</id>
    <descripcion_v>Serviu en un plat fondo les mandonguilles acompanyades de la crema de carabassa.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>42</id_receta>
    <orden>1</orden>
    <descripcion>En un bol, mezclar la zanahoria pelada y rallada, con el queso rallado.</descripcion>
    <id>31.036</id>
    <descripcion_v>En un bol, mescleu la carlota pelada i ratllada amb el formatge ratllat.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>42</id_receta>
    <orden>2</orden>
    <descripcion>Añadir la cebolla picada y la albahaca.</descripcion>
    <id>31.037</id>
    <descripcion_v>Afegiu-hi la ceba picada i l'alfàbega.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>42</id_receta>
    <orden>3</orden>
    <descripcion>Batir ligeramente el huevo y añadirlo a la mezcla anterior. Salar y remover.</descripcion>
    <id>31.038</id>
    <descripcion_v>Bateu lleugerament l'ou i afegiu-lo a la mescla anterior. Saleu-ho i remeneu-ho.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>42</id_receta>
    <orden>4</orden>
    <descripcion>Añadir el pan rallado (reservar una pequeña parte para el rebozado), y mezclar hasta conseguir una masa compacta.</descripcion>
    <id>31.039</id>
    <descripcion_v>Afegiu-hi el pa ratllat (reserveu-ne una xicoteta part per a l'arrebossat) i mescleu-ho fins a aconseguir una pasta compacta.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>42</id_receta>
    <orden>5</orden>
    <descripcion>Dar forma a las albóndigas, rebozar y freír en una sartén con aceite bien caliente.</descripcion>
    <id>31.040</id>
    <descripcion_v>Doneu forma a les mandonguilles, arrebosseu-les i fregiu-les en una paella amb oli ben calent.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>679</id_receta>
    <orden>1</orden>
    <descripcion>Coloca en un bol el requesón, las yemas, el queso rallado, la sal y la nuez moscada. Mezcla todo. Por último incorpora la harina.</descripcion>
    <id>31.041</id>
    <descripcion_v>Col·loca en un bol el brull, els rovells, el formatge ratllat, la sal i l’anou moscada. Mescla-ho tot. Finalment incorpora-hi la farina.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>679</id_receta>
    <orden>2</orden>
    <descripcion>Con las manos enharinadas, haz bolitas pequeñas y cocina en agua con sal hirviendo durante 10 minutos. Ni bien suban a la superficie, ya que tiene poca cantidad de harina, retíralas.</descripcion>
    <id>31.042</id>
    <descripcion_v>Amb les mans enfarinades, fes boletes menudes i cou-les en aigua bullint amb sal durant 10 minuts. Només pugen a la superfície, ja que tenen poca quantitat de farina, retira-les.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>679</id_receta>
    <orden>3</orden>
    <descripcion>Aparte prepara la salsa. Coloca el puré de tomate en una cacerola con la nata, el jamón cortado en tiritas, el coñac, la sal y la pimienta.</descripcion>
    <id>31.043</id>
    <descripcion_v>A banda prepara la salsa. Col•loca el puré de tomaca en una cassola amb la nata, el pernil de York tallat en tiretes, el conyac, la sal i el pebre.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>679</id_receta>
    <orden>4</orden>
    <descripcion>Coloca las albóndigas en una fuente cubierta de salsa y sirve caliente.</descripcion>
    <id>31.044</id>
    <descripcion_v>Col·loca les mandonguilles en una plata coberta de salsa i servix-les calentes.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>914</id_receta>
    <orden>1</orden>
    <descripcion>Hidrata la soja en caldo o en agua una hora. Escurre y coloca en un cuenco. Añade el perejil, el diente de ajo picado y la mitad del pan rallado.</descripcion>
    <id>31.045</id>
    <descripcion_v>Hidrata la soja en caldo o en aigua una hora. Escorre-la i col·loca-la en un bol. Afig-hi el julivert, l’all picat i la meitat del pa ratllat.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>914</id_receta>
    <orden>2</orden>
    <descripcion>Salpimienta y obtén una masa incorporando el resto del pan rallado.</descripcion>
    <id>31.046</id>
    <descripcion_v>Condimenta-ho i obtín una massa incorporant-hi la resta del pa ratllat.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>914</id_receta>
    <orden>3</orden>
    <descripcion>Desmiga el pan en un cuenco, riega con la bebida de soja, deja que se empape y escurre agrupando la miga con la mano. Incorpora a la mezcla amasándolo todo. Toma porciones de la masa y da forma de albóndigas. Reboza con harina y deja reposar unos minutos. Dora en una sartén con aceite. Calienta la salsa de tomate en una cazuela e introduce las albóndigas y cocina 10-15 minutos a fuego lento.</descripcion>
    <id>31.047</id>
    <descripcion_v>Esmolla el pa en un bol, rega’l amb la beguda de soja, deixa que es xope i escorre’l prement la molla amb la mà. Incorpora’l a la mescla pastant-ho tot. Agafa porcions de la massa i dóna’ls forma de mandonguilles. Arrebossa-les amb farina i deixa-les reposar uns minuts. Daura-les en una paella amb oli. Calfa la salsa de tomaca en una cassola, fica-hi les mandonguilles i cuina-les 10-15 minuts a foc lent.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>604</id_receta>
    <orden>1</orden>
    <descripcion>Pela y corta las alcachofas en cuartos . Colócalas en una cazuela con el aceite, la sal, el vaso de agua, los ajos finamente picados, el perejil picado, el zumo de limón y la pimienta.</descripcion>
    <id>31.048</id>
    <descripcion_v>Pela i talla les carxofes en quarts. Col•loca-les en una cassola amb l’oli, la sal, el got d’aigua, els alls finament picats, el julivert picat, el suc de llima i el pebre.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>604</id_receta>
    <orden>2</orden>
    <descripcion>Cocina a fuego suave con la cazuela tapada(20 minutos);  en cuanto la cocción esté avanzada, esparce el pan rallado y termina de cocer(10 minutos).</descripcion>
    <id>31.049</id>
    <descripcion_v>Cuina-les a foc suau amb la cassola tapada (20 minuts);  quan la cocció estiga avançada, escampa-hi el pa ratllat i acaba-ho de coure (10 minuts).</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>1.004</id_receta>
    <orden>1</orden>
    <descripcion>Limpia las alcachofas, quítales las hojas exteriores y las puntas,  córtalas a cuartos. Mientras las limpias todas, puedes poner los cuartos en un bol con agua que tenga un chorro de zumo de limón para evitar que se pongan negras.</descripcion>
    <id>31.050</id>
    <descripcion_v>Neteja les carxofes, lleva’n les fulles exteriors i les puntes i talla-les en quarts. Mentre les neteges totes, pots posar els quarts en un bol amb aigua que tinga un raig de suc de llima per a evitar que es facen negres.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>1.004</id_receta>
    <orden>2</orden>
    <descripcion>En una cazuela grande y que tenga tapa coloca las alcachofas, el aceite, los ajos laminados, el perejil finamente picado, el zumo del limón, sal y pimienta a gusto, y agua hasta cubrir.</descripcion>
    <id>31.051</id>
    <descripcion_v>En una cassola gran i que tinga tapa, col·loca les carxofes, l’oli, els alls laminats, el julivert picat fi, el suc de la llima, sal i pebre al gust, i aigua fins a cobrir.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>1.004</id_receta>
    <orden>3</orden>
    <descripcion>Tapa la cazuela y deja que cueza todo a fuego lento durante unos 25 o 30 minutos, hasta que las alcachofas estén tiernas . Vigila que no se quede sin agua y si ves que le hace falta le añades más.</descripcion>
    <id>31.052</id>
    <descripcion_v>Tapa la cassola i deixa que es coga tot a foc lent durant uns 25 o 30 minuts, fins que les carxofes estiguen tendres . Vigila que no es quede sense aigua i si veus que en falta, afig-n’hi més.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>1.004</id_receta>
    <orden>4</orden>
    <descripcion>Cuando estén tiernas añade el pan rallado, más o menos en función del agua que tengas en la cazuela y  deja en el fuego durante unos 5 minutos más.</descripcion>
    <id>31.053</id>
    <descripcion_v>Quan estiguen tendres, afig-hi el pa ratllat, més o menys en funció de l’aigua que tingues a la cassola i deixa-ho al foc durant uns 5 minuts més.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>945</id_receta>
    <orden>1</orden>
    <descripcion>En caso de usarlos naturales, limpia y cuece las alcachofas, pela los tomates y asa el pimiento rojo. Si se usan productos envasados, escurre bien los corazones de alcachofa y pártelos por la mitad. Pica la cebolleta y el diente de ajo.</descripcion>
    <id>31.054</id>
    <descripcion_v>En cas d’utilitzar-los naturals, neteja i cou les carxofes, pela les tomaques i torra el pimentó roig. Si s’usen productes envasats, escorre bé els cors de carxofa i partix-los per la meitat. Pica la ceba tendra i l’all.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>945</id_receta>
    <orden>2</orden>
    <descripcion>Calienta un poco de aceite en una sartén y cocina la cebolleta con el diente de ajo unos minutos. Añade el tomate y da unas vueltas. Rehoga con el vino, salpimienta ligeramente y deja cocer todo unos 10 minutos.</descripcion>
    <id>31.055</id>
    <descripcion_v>Calfa una miqueta d’oli en una paella i cou-hi la ceba tendra amb l’all uns minuts. Afig-hi la tomaca i remena-la un poc. Ofega-ho amb el vi, condimenta-ho lleugerament i deixa-ho coure tot uns 10 minuts.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>945</id_receta>
    <orden>3</orden>
    <descripcion>Bate en un cuenco el vinagre con el aceite, un poco de vino y las hierbas provenzales. Mezcla en una fuente las alcachofas con la salsa, añade el pimiento rojo cortado en tiras y aliña. Salpimienta al gusto y deja enfriar antes de servir.</descripcion>
    <id>31.056</id>
    <descripcion_v>Bat en un bol el vinagre amb l’oli, una miqueta de vi i les herbes provençals. Mescla en una plata les carxofes amb la salsa, afig-hi el pimentó roig tallat en tires i adoba-ho. Condimenta-ho al gust i deixa-ho refredar abans de servir.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>1.144</id_receta>
    <orden>1</orden>
    <descripcion>Elimina las hojas exteriores y la base del tallo de las alcachofas. Divídelas en 4 trozos.</descripcion>
    <id>31.057</id>
    <descripcion_v>Elimina les fulles exteriors de les carxofes i la base de la tija. Dividix-les en 4 trossos.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>1.144</id_receta>
    <orden>2</orden>
    <descripcion>Ponlas a cocer durante 10 minutos (depende del tamaño) en una cazuela con agua que las cubra. Añade al agua 1 cucharada de harina, otra de aceite, el zumo de un limón y un poco de sal, todo bien desleído y mezclado previamente.</descripcion>
    <id>31.058</id>
    <descripcion_v>Posa-les a bullir durant 10 minuts (segons la mida) en una cassola amb aigua que les cobrisca. Afig a l’aigua 1 cullerada de farina, una altra d’oli, el suc d’un llima i una mica de sal, tot ben desfet i barrejat prèviament.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>1.144</id_receta>
    <orden>3</orden>
    <descripcion>En una cazuela con el resto del aceite, sofríe la cebolla y los ajos picados muy finos. Cuando estén dorados, añade el vino y las almejas, y ve removiendo hasta que estén todas abiertas.</descripcion>
    <id>31.059</id>
    <descripcion_v>En una cassola amb la resta de l’oli, sofrig la ceba i els alls picats molt fins. Quan estiguen daurats, afig-hi el vi i les cloïsses, i vés remenant fins que estiguen totes obertes.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>1.144</id_receta>
    <orden>4</orden>
    <descripcion>Agrega las alcachofas bien escurridas y el vaso de caldo, tapa la cazuela y deja cocinar 5 minutos a fuego muy bajo. Después, destapa la cazuela, sube el fuego y cuece algunos minutos más hasta que el caldo quede concentrado.</descripcion>
    <id>31.060</id>
    <descripcion_v>Tira-hi les carxofes ben escorregudes i el got de caldo, tapa la cassola i deixa-ho coure 5 minuts a foc molt baix. Després, destapa la cassola, apuja el foc i cuina-ho alguns minuts més fins que el caldo quede concentrat.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>703</id_receta>
    <orden>1</orden>
    <descripcion>Pon a depurar las almejas en un cuenco con agua y buen puñado de sal gruesa.</descripcion>
    <id>31.061</id>
    <descripcion_v>Posa a depurar les cloïsses en un bol amb aigua i un bon grapat de sal grossa.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>703</id_receta>
    <orden>2</orden>
    <descripcion>Pela la cebolla, pícala muy fina y ponla en una cazuela plana, a fuego muy bajo. Déjala rehogar hasta que empiece a transparentarse; añade los ajos, picados también muy finos.</descripcion>
    <id>31.062</id>
    <descripcion_v>Pela la ceba, pica-la molt fina i posa-la en una cassola plana, a foc molt baix. Deixa-la ofegar fins que comence a transparentar-se; afig-hi els alls, picats també molt fins.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>703</id_receta>
    <orden>3</orden>
    <descripcion>Mientras, limpia los boletus con un trapo húmedo, y si el pie está muy sucio de tierra, ráspalo con un cuchillo. Aprovecha al máximo los pies, ya que en esta especie son tan buenos como el sombrero. Corta las setas a láminas finas.</descripcion>
    <id>31.063</id>
    <descripcion_v>Mentrestant, neteja els ceps amb un drap humit i, si el peu està molt brut de terra, rasca'l amb un ganivet. Aprofita'n al màxim els peus, ja que en aquesta espècie són tan bons com el barret. Talla els bolets en làmines fines.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>703</id_receta>
    <orden>4</orden>
    <descripcion>Cuando la cebolla y los ajos comiencen a dorarse, agrega las setas y mezcla bien. Deja cocer, siempre a fuego, durante 5 minutos, removiendo de vez en cuando.</descripcion>
    <id>31.064</id>
    <descripcion_v>Quan la ceba i els alls comencen a daurar-se, agrega-hi els bolets i barreja-ho bé. Deixa-ho coure, sempre a foc, durant 5 minuts, remenant de tant en tant.</descripcion_v>
    <trial448>T</trial448>
  </DATA_RECORD>
  <DATA_RECORD>
    <id_receta>703</id_receta>
    <orden>5</orden>