<?xml version="1.0" ?>
<!DOCTYPE select_rmt_nombre_tipo_plato_r_from_rct_r_rct_m_tipoplato_rmt_where_r_id_platip_rmt_id_ [
  <!ELEMENT select_rmt_nombre_tipo_plato_r_from_rct_r_rct_m_tipoplato_rmt_where_r_id_platip_rmt_id_ (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (tipo_plato?,id?,descripcion?,comensales?,id_platip?,id_tipprep?,energia?,carbohidratos?,proteinas?,grasas?,estado?,essimple?,fecha_publi?,descripcion_publi?,descripcion_v?,descripcion_publi_v?,url_amigable?,fibra?,colesterol?,ingrediente_principal?,perfil?,tipo_plato?,basico?,contenido?,contenido_v?,autor?,estacion?,publicado?,necesidades?,localidad?,tipo_comida?,almidon?,grasa_total?,ags?,agm?,agp?,agp_div_ags?,agp_mas_agm_div_ags?,agua?,alcohol?,calcio?,hierro?,yodo?,magnesio?,zinc?,selenio?,sodio?,potasio?,fosforo?,fluor?,vitamina_b1?,vitamina_b2?,niacina?,ac_pantotenico?,vitamina_b6?,acido_folico?,vitamina_b12?,biotina?,vitamina_c?,vitamina_a?,retinol?,carotenos?,vitamina_d?,vitamina_e?,vitamina_k?,omega_3?,omega_6?,omega_3_div_6?,cafeina?,teobromina?,azucares_simples?,fitoesteroles?,beta_sitosterol?,campesterol?,estigmasterol?,estigmaesterol_d7?,brasica_esterol?,avenaesterol_d5?,avenaesterol_d7?,quercitina?,quitar_medicos?,lleva_guarnicion?,trial445?)+>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT comensales (#PCDATA)>
  <!ELEMENT id_platip (#PCDATA)>
  <!ELEMENT id_tipprep (#PCDATA)>
  <!ELEMENT energia (#PCDATA)>
  <!ELEMENT carbohidratos (#PCDATA)>
  <!ELEMENT proteinas (#PCDATA)>
  <!ELEMENT grasas (#PCDATA)>
  <!ELEMENT estado (#PCDATA)>
  <!ELEMENT essimple (#PCDATA)>
  <!ELEMENT fecha_publi (#PCDATA)>
  <!ELEMENT descripcion_publi (#PCDATA)>
  <!ELEMENT descripcion_v (#PCDATA)>
  <!ELEMENT descripcion_publi_v (#PCDATA)>
  <!ELEMENT url_amigable (#PCDATA)>
  <!ELEMENT fibra (#PCDATA)>
  <!ELEMENT colesterol (#PCDATA)>
  <!ELEMENT ingrediente_principal (#PCDATA)>
  <!ELEMENT perfil (#PCDATA)>
  <!ELEMENT tipo_plato (#PCDATA)>
  <!ELEMENT basico (#PCDATA)>
  <!ELEMENT contenido (#PCDATA)>
  <!ELEMENT contenido_v (#PCDATA)>
  <!ELEMENT autor (#PCDATA)>
  <!ELEMENT estacion (#PCDATA)>
  <!ELEMENT publicado (#PCDATA)>
  <!ELEMENT necesidades (#PCDATA)>
  <!ELEMENT localidad (#PCDATA)>
  <!ELEMENT tipo_comida (#PCDATA)>
  <!ELEMENT almidon (#PCDATA)>
  <!ELEMENT grasa_total (#PCDATA)>
  <!ELEMENT ags (#PCDATA)>
  <!ELEMENT agm (#PCDATA)>
  <!ELEMENT agp (#PCDATA)>
  <!ELEMENT agp_div_ags (#PCDATA)>
  <!ELEMENT agp_mas_agm_div_ags (#PCDATA)>
  <!ELEMENT agua (#PCDATA)>
  <!ELEMENT alcohol (#PCDATA)>
  <!ELEMENT calcio (#PCDATA)>
  <!ELEMENT hierro (#PCDATA)>
  <!ELEMENT yodo (#PCDATA)>
  <!ELEMENT magnesio (#PCDATA)>
  <!ELEMENT zinc (#PCDATA)>
  <!ELEMENT selenio (#PCDATA)>
  <!ELEMENT sodio (#PCDATA)>
  <!ELEMENT potasio (#PCDATA)>
  <!ELEMENT fosforo (#PCDATA)>
  <!ELEMENT fluor (#PCDATA)>
  <!ELEMENT vitamina_b1 (#PCDATA)>
  <!ELEMENT vitamina_b2 (#PCDATA)>
  <!ELEMENT niacina (#PCDATA)>
  <!ELEMENT ac_pantotenico (#PCDATA)>
  <!ELEMENT vitamina_b6 (#PCDATA)>
  <!ELEMENT acido_folico (#PCDATA)>
  <!ELEMENT vitamina_b12 (#PCDATA)>
  <!ELEMENT biotina (#PCDATA)>
  <!ELEMENT vitamina_c (#PCDATA)>
  <!ELEMENT vitamina_a (#PCDATA)>
  <!ELEMENT retinol (#PCDATA)>
  <!ELEMENT carotenos (#PCDATA)>
  <!ELEMENT vitamina_d (#PCDATA)>
  <!ELEMENT vitamina_e (#PCDATA)>
  <!ELEMENT vitamina_k (#PCDATA)>
  <!ELEMENT omega_3 (#PCDATA)>
  <!ELEMENT omega_6 (#PCDATA)>
  <!ELEMENT omega_3_div_6 (#PCDATA)>
  <!ELEMENT cafeina (#PCDATA)>
  <!ELEMENT teobromina (#PCDATA)>
  <!ELEMENT azucares_simples (#PCDATA)>
  <!ELEMENT fitoesteroles (#PCDATA)>
  <!ELEMENT beta_sitosterol (#PCDATA)>
  <!ELEMENT campesterol (#PCDATA)>
  <!ELEMENT estigmasterol (#PCDATA)>
  <!ELEMENT estigmaesterol_d7 (#PCDATA)>
  <!ELEMENT brasica_esterol (#PCDATA)>
  <!ELEMENT avenaesterol_d5 (#PCDATA)>
  <!ELEMENT avenaesterol_d7 (#PCDATA)>
  <!ELEMENT quercitina (#PCDATA)>
  <!ELEMENT quitar_medicos (#PCDATA)>
  <!ELEMENT lleva_guarnicion (#PCDATA)>
  <!ELEMENT trial445 (#PCDATA)>
]>
<select_rmt_nombre_tipo_plato_r_from_rct_r_rct_m_tipoplato_rmt_where_r_id_platip_rmt_id_>
  <DATA_RECORD>
    <nombre>S/C</nombre>
    <id>6</id>
    <descripcion>Arroz a banda</descripcion>
    <comensales>4</comensales>
    <id_platip>0</id_platip>
    <id_tipprep></id_tipprep>
    <energia>540</energia>
    <carbohidratos>68,8000030518</carbohidratos>
    <proteinas>27,2999992371</proteinas>
    <grasas>16,7999992371</grasas>
    <estado>1</estado>
    <essimple>0</essimple>
    <fecha_publi>2013-04-25 00:00:00</fecha_publi>
    <descripcion_publi></descripcion_publi>
    <descripcion_v>Arròs a banda</descripcion_v>
    <descripcion_publi_v>&amp;lt;p&amp;gt;Perquè no et calfes el cap cada dia a l'hora de cuinar, et proposem receptes pràctiques i senzilles per a dur una dieta sana i equilibrada, siga quin siga el teu estil de vida. Disfruta-les!&amp;lt;/p&amp;gt;</descripcion_publi_v>
    <url_amigable>arroz-a-banda</url_amigable>
    <fibra>2,2000000477</fibra>
    <colesterol>73,6999969482</colesterol>
    <ingrediente_principal>24</ingrediente_principal>
    <perfil>252</perfil>
    <tipo_plato>4</tipo_plato>
    <basico>0</basico>
    <contenido>Cocer en un puchero con agua, el pescado, la cebolla pelada y troceada, el laurel y un poco de sal, durante unos 20 minutos</contenido>
    <contenido_v>Coeu en una olla amb aigua el peix, la ceba pelada i trossejada, el llorer i un poc de sal, durant uns 20 minuts</contenido_v>
    <autor></autor>
    <estacion>30</estacion>
    <publicado>1</publicado>
    <necesidades>62</necesidades>
    <localidad></localidad>
    <tipo_comida>2</tipo_comida>
    <almidon>65,5</almidon>
    <grasa_total>16,7999992371</grasa_total>
    <ags>2,7000000477</ags>
    <agm>8,8999996185</agm>
    <agp>3,0999999046</agp>
    <agp_div_ags>1,1499999762</agp_div_ags>
    <agp_mas_agm_div_ags>4,4400000572</agp_mas_agm_div_ags>
    <agua>528</agua>
    <alcohol>0</alcohol>
    <calcio>49,2000007629</calcio>
    <hierro>1,7999999523</hierro>
    <yodo>51,9000015259</yodo>
    <magnesio>60,5999984741</magnesio>
    <zinc>2,2999999523</zinc>
    <selenio>60</selenio>
    <sodio>265</sodio>
    <potasio>545</potasio>
    <fosforo>446</fosforo>
    <fluor>150</fluor>
    <vitamina_b1>0,1800000072</vitamina_b1>
    <vitamina_b2>0,1599999964</vitamina_b2>
    <niacina>14,1999998093</niacina>
    <ac_pantotenico>1,2000000477</ac_pantotenico>
    <vitamina_b6>0,6999999881</vitamina_b6>
    <acido_folico>35,4000015259</acido_folico>
    <vitamina_b12>2,7999999523</vitamina_b12>
    <biotina>7</biotina>
    <vitamina_c>4,6999998093</vitamina_c>
    <vitamina_a>56,2000007629</vitamina_a>
    <retinol>16,2999992371</retinol>
    <carotenos>53,2999992371</carotenos>
    <vitamina_d>3,9000000954</vitamina_d>
    <vitamina_e>3,5999999046</vitamina_e>
    <vitamina_k>6,9000000954</vitamina_k>
    <omega_3>1,3999999762</omega_3>
    <omega_6>1,7000000477</omega_6>
    <omega_3_div_6>0,8199999928</omega_3_div_6>
    <cafeina>0</cafeina>
    <teobromina>0</teobromina>
    <azucares_simples>3,2999999523</azucares_simples>
    <fitoesteroles>7,9000000954</fitoesteroles>
    <beta_sitosterol>5,5</beta_sitosterol>
    <campesterol>0,4600000083</campesterol>
    <estigmasterol>0</estigmasterol>
    <estigmaesterol_d7>0</estigmaesterol_d7>
    <brasica_esterol>0</brasica_esterol>
    <avenaesterol_d5>0</avenaesterol_d5>
    <avenaesterol_d7>0</avenaesterol_d7>
    <quercitina>0</quercitina>
    <quitar_medicos></quitar_medicos>
    <lleva_guarnicion></lleva_guarnicion>
    <trial445>T</trial445>
  </DATA_RECORD>
  <DATA_RECORD>
    <nombre>S/C</nombre>
    <id>19</id>
    <descripcion>Milhojas de morcilla</descripcion>
    <comensales>4</comensales>
    <id_platip>0</id_platip>
    <id_tipprep></id_tipprep>
    <energia>1.194</energia>
    <carbohidratos>83,3000030518</carbohidratos>
    <proteinas>22,3999996185</proteinas>
    <grasas>84,1999969482</grasas>
    <estado>1</estado>
    <essimple>0</essimple>
    <fecha_publi>2013-04-25 00:00:00</fecha_publi>
    <descripcion_publi></descripcion_publi>
    <descripcion_v>Pasta fullada amb botifarra</descripcion_v>
    <descripcion_publi_v>Perquè no et calfes el cap cada dia a l'hora de cuinar, et proposem receptes pràctiques i senzilles per a dur una dieta sana i equilibrada, siga quin siga el teu estil de vida. Disfruta-les!</descripcion_publi_v>
    <url_amigable>milhojas-de-morcilla</url_amigable>
    <fibra>6,9000000954</fibra>
    <colesterol>133</colesterol>
    <ingrediente_principal>21</ingrediente_principal>
    <perfil>212</perfil>
    <tipo_plato>2</tipo_plato>
    <basico>0</basico>
    <contenido>Vaciar las morcillas. Pelar y partir las cebollas en tiras.</contenido>
    <contenido_v>Buideu les botifarres. Peleu les cebes i partiu-les en tires.</contenido_v>
    <autor></autor>
    <estacion>30</estacion>
    <publicado>1</publicado>
    <necesidades>32</necesidades>
    <localidad></localidad>
    <tipo_comida>1</tipo_comida>
    <almidon>72,1999969482</almidon>
    <grasa_total>84,1999969482</grasa_total>
    <ags>18,5</ags>
    <agm>23,7000007629</agm>
    <agp>34,2999992371</agp>
    <agp_div_ags>1,8500000238</agp_div_ags>
    <agp_mas_agm_div_ags>3,1400001049</agp_mas_agm_div_ags>
    <agua>212</agua>
    <alcohol>0</alcohol>
    <calcio>89,1999969482</calcio>
    <hierro>14,5</hierro>
    <yodo>41,2000007629</yodo>
    <magnesio>75,4000015259</magnesio>
    <zinc>3,0999999046</zinc>
    <selenio>48,2999992371</selenio>
    <sodio>1.164</sodio>
    <potasio>587</potasio>
    <fosforo>248</fosforo>
    <fluor>15,6999998093</fluor>
    <vitamina_b1>0,6000000238</vitamina_b1>
    <vitamina_b2>0,5600000024</vitamina_b2>
    <niacina>14,1999998093</niacina>
    <ac_pantotenico>1,1000000238</ac_pantotenico>
    <vitamina_b6>0,2800000012</vitamina_b6>
    <acido_folico>87,5999984741</acido_folico>
    <vitamina_b12>0,8799999952</vitamina_b12>
    <biotina>8</biotina>
    <vitamina_c>9,6000003815</vitamina_c>
    <vitamina_a>36,7000007629</vitamina_a>
    <retinol>34,2999992371</retinol>
    <carotenos>12,8000001907</carotenos>
    <vitamina_d>1,7000000477</vitamina_d>
    <vitamina_e>6</vitamina_e>
    <vitamina_k>28,8999996185</vitamina_k>
    <omega_3>3,5999999046</omega_3>
    <omega_6>30,6000003815</omega_6>
    <omega_3_div_6>0,1199999973</omega_3_div_6>
    <cafeina>0</cafeina>
    <teobromina>0</teobromina>
    <azucares_simples>10,6000003815</azucares_simples>
    <fitoesteroles>20,5</fitoesteroles>
    <beta_sitosterol>16,3999996185</beta_sitosterol>
    <campesterol>1,3999999762</campesterol>
    <estigmasterol>0</estigmasterol>
    <estigmaesterol_d7>0</estigmaesterol_d7>
    <brasica_esterol>0</brasica_esterol>
    <avenaesterol_d5>0</avenaesterol_d5>
    <avenaesterol_d7>0</avenaesterol_d7>
    <quercitina>0</quercitina>
    <quitar_medicos></quitar_medicos>
    <lleva_guarnicion></lleva_guarnicion>
    <trial445>T</trial445>
  </DATA_RECORD>
  <DATA_RECORD>
    <nombre>S/C</nombre>
    <id>42</id>
    <descripcion>Albóndigas de queso y zanahoria</descripcion>
    <comensales>4</comensales>
    <id_platip>0</id_platip>
    <id_tipprep>1</id_tipprep>
    <energia>433</energia>
    <carbohidratos>18</carbohidratos>
    <proteinas>14,5</proteinas>
    <grasas>32,7999992371</grasas>
    <estado>1</estado>
    <essimple>0</essimple>
    <fecha_publi>2013-04-25 00:00:00</fecha_publi>
    <descripcion_publi></descripcion_publi>
    <descripcion_v>Mandonguilles de formatge i carlota</descripcion_v>
    <descripcion_publi_v>Perquè no et calfes el cap cada dia a l'hora de cuinar, et proposem receptes pràctiques i senzilles per a dur una dieta sana i equilibrada, siga quin siga el teu estil de vida. Disfruta-les!</descripcion_publi_v>
    <url_amigable>albondigas-de-queso-y-zanahoria</url_amigable>
    <fibra>4,3000001907</fibra>
    <colesterol>189</colesterol>
    <ingrediente_principal>8</ingrediente_principal>
    <perfil>117</perfil>
    <tipo_plato>2</tipo_plato>
    <basico>0</basico>
    <contenido>En un bol, mezclar la zanahoria pelada y rallada, con el queso rallado. Añadir la cebolla picada y la albahaca.</contenido>
    <contenido_v>En un bol, mescleu la carlota pelada i ratllada amb el formatge ratllat. Afegiu-hi la ceba picada i l'alfàbega.</contenido_v>
    <autor></autor>
    <estacion>30</estacion>
    <publicado>1</publicado>
    <necesidades></necesidades>
    <localidad></localidad>
    <tipo_comida>8</tipo_comida>
    <almidon>6,3000001907</almidon>
    <grasa_total>32,7999992371</grasa_total>
    <ags>8,3000001907</ags>
    <agm>16,3999996185</agm>
    <agp>3,4000000954</agp>
    <agp_div_ags>0,4099999964</agp_div_ags>
    <agp_mas_agm_div_ags>2,3900001049</agp_mas_agm_div_ags>
    <agua>178</agua>
    <alcohol>0</alcohol>
    <calcio>282</calcio>
    <hierro>1,8999999762</hierro>
    <yodo>16,2999992371</yodo>
    <magnesio>33,2999992371</magnesio>
    <zinc>2,2999999523</zinc>
    <selenio>10,5</selenio>
    <sodio>338</sodio>
    <potasio>550</potasio>
    <fosforo>288</fosforo>
    <fluor>54,5</fluor>
    <vitamina_b1>0,1400000006</vitamina_b1>
    <vitamina_b2>0,3000000119</vitamina_b2>
    <niacina>4,4000000954</niacina>
    <ac_pantotenico>1,2000000477</ac_pantotenico>
    <vitamina_b6>0,3000000119</vitamina_b6>
    <acido_folico>47</acido_folico>
    <vitamina_b12>1,2999999523</vitamina_b12>
    <biotina>17,3999996185</biotina>
    <vitamina_c>10,1999998093</vitamina_c>
    <vitamina_a>2.051</vitamina_a>
    <retinol>140</retinol>
    <carotenos>11.438</carotenos>
    <vitamina_d>0,7699999809</vitamina_d>
    <vitamina_e>4,1999998093</vitamina_e>
    <vitamina_k>44,5</vitamina_k>
    <omega_3>0,400000006</omega_3>
    <omega_6>2,9000000954</omega_6>
    <omega_3_div_6>0,1400000006</omega_3_div_6>
    <cafeina>0</cafeina>
    <teobromina>0</teobromina>
    <azucares_simples>10,5</azucares_simples>
    <fitoesteroles>18,3999996185</fitoesteroles>
    <beta_sitosterol>11,3000001907</beta_sitosterol>
    <campesterol>1,5</campesterol>
    <estigmasterol>3,9000000954</estigmasterol>
    <estigmaesterol_d7>0</estigmaesterol_d7>
    <brasica_esterol>0</brasica_esterol>
    <avenaesterol_d5>0</avenaesterol_d5>
    <avenaesterol_d7>0</avenaesterol_d7>
    <quercitina>0</quercitina>
    <quitar_medicos></quitar_medicos>
    <lleva_guarnicion></lleva_guarnicion>
    <trial445>T</trial445>
  </DATA_RECORD>
  <DATA_RECORD>
    <nombre>S/C</nombre>
    <id>49</id>
    <descripcion>Ensalada de jamón ibérico con aguacate</descripcion>
    <comensales>4</comensales>
    <id_platip>0</id_platip>
    <id_tipprep>1</id_tipprep>
    <energia>392</energia>
    <carbohidratos>10,6000003815</carbohidratos>
    <proteinas>18,5</proteinas>
    <grasas>32,2000007629</grasas>
    <estado>1</estado>
    <essimple>0</essimple>
    <fecha_publi>2013-04-25 00:00:00</fecha_publi>
    <descripcion_publi></descripcion_publi>
    <descripcion_v>Ensalada de pernil ibèric amb alvocat</descripcion_v>
    <descripcion_publi_v>Perquè no et calfes el cap cada dia a l'hora de cuinar, et proposem receptes pràctiques i senzilles per a dur una dieta sana i equilibrada, siga quin siga el teu estil de vida. Disfruta-les!</descripcion_publi_v>
    <url_amigable>ensalada-de-jamon-iberico-con-aguacate</url_amigable>
    <fibra>7,5999999046</fibra>
    <colesterol>150</colesterol>
    <ingrediente_principal>36</ingrediente_principal>
    <perfil>244</perfil>
    <tipo_plato>2</tipo_plato>
    <basico>0</basico>
    <contenido>Hervir los huevos y dejar enfriar. Pelar los aguacates y cortarlos en rodajas.</contenido>
    <contenido_v>Bulliu els ous i deixeu que es refreden.  Peleu els alvocats i talleu-los en rodanxes.</contenido_v>
    <autor></autor>
    <estacion>6</estacion>
    <publicado>1</publicado>
    <necesidades>50</necesidades>
    <localidad></localidad>
    <tipo_comida>6</tipo_comida>
    <almidon>8,3999996185</almidon>
    <grasa_total>32,2000007629</grasa_total>
    <ags>5,6999998093</ags>
    <agm>20,6000003815</agm>
    <agp>3,5999999046</agp>
    <agp_div_ags>0,6299999952</agp_div_ags>
    <agp_mas_agm_div_ags>4,25</agp_mas_agm_div_ags>
    <agua>156</agua>
    <alcohol>0</alcohol>
    <calcio>41,0999984741</calcio>
    <hierro>2,5999999046</hierro>
    <yodo>12,6999998093</yodo>
    <magnesio>46,7000007629</magnesio>
    <zinc>2</zinc>
    <selenio>3,2999999523</selenio>
    <sodio>1.222</sodio>
    <potasio>736</potasio>
    <fosforo>243</fosforo>
    <fluor>36,4000015259</fluor>
    <vitamina_b1>0,4600000083</vitamina_b1>
    <vitamina_b2>0,4099999964</vitamina_b2>
    <niacina>6</niacina>
    <ac_pantotenico>1,7000000477</ac_pantotenico>
    <vitamina_b6>0,6800000072</vitamina_b6>
    <acido_folico>101</acido_folico>
    <vitamina_b12>0,5500000119</vitamina_b12>
    <biotina>17,7999992371</biotina>
    <vitamina_c>11,8000001907</vitamina_c>
    <vitamina_a>66,9000015259</vitamina_a>
    <retinol>58,7000007629</retinol>
    <carotenos>61</carotenos>
    <vitamina_d>0,4699999988</vitamina_d>
    <vitamina_e>3,4000000954</vitamina_e>
    <vitamina_k>36,4000015259</vitamina_k>
    <omega_3>0,3700000048</omega_3>
    <omega_6>3,2999999523</omega_6>
    <omega_3_div_6>0,1099999994</omega_3_div_6>
    <cafeina>0</cafeina>
    <teobromina>0</teobromina>
    <azucares_simples>2</azucares_simples>
    <fitoesteroles>2,7999999523</fitoesteroles>
    <beta_sitosterol>83</beta_sitosterol>
    <campesterol>5,5</campesterol>
    <estigmasterol>2,0999999046</estigmasterol>
    <estigmaesterol_d7>0</estigmaesterol_d7>
    <brasica_esterol>0</brasica_esterol>
    <avenaesterol_d5>0</avenaesterol_d5>
    <avenaesterol_d7>0</avenaesterol_d7>
    <quercitina>0</quercitina>
    <quitar_medicos></quitar_medicos>
    <lleva_guarnicion></lleva_guarnicion>
    <trial445>T</trial445>
  </DATA_RECORD>
  <DATA_RECORD>
    <nombre>S/C</nombre>
    <id>53</id>
    <descripcion>Muffins de queso fresco y nueces</descripcion>
    <comensales>4</comensales>
    <id_platip>0</id_platip>
    <id_tipprep></id_tipprep>
    <energia>692</energia>
    <carbohidratos>53,2000007629</carbohidratos>
    <proteinas>20,8999996185</proteinas>
    <grasas>43,5</grasas>
    <estado>1</estado>
    <essimple>0</essimple>
    <fecha_publi>2013-04-25 00:00:00</fecha_publi>
    <descripcion_publi></descripcion_publi>
    <descripcion_v>Muffins de formatge fresc i anous</descripcion_v>
    <descripcion_publi_v>&amp;lt;p&amp;gt;Perquè no et calfes el cap cada dia a l'hora de cuinar, et proposem receptes pràctiques i senzilles per a dur una dieta sana i equilibrada, siga quin siga el teu estil de vida. Disfruta-les!&amp;lt;/p&amp;gt;</descripcion_publi_v>
    <url_amigable>muffins-de-queso-fresco-y-nueces</url_amigable>
    <fibra>2,0999999046</fibra>
    <colesterol>50,2000007629</colesterol>
    <ingrediente_principal>24</ingrediente_principal>
    <perfil>244</perfil>
    <tipo_plato>32</tipo_plato>
    <basico>0</basico>
    <contenido>Separar 6 nueces (que utilizaremos para decorar) y picar el resto. Deshacer los bizcochos de soletilla.</contenido>
    <contenido_v>Separeu 6 anous (que utilitzareu per a decorar) i piqueu les altres.  Desfeu els melindros.</contenido_v>
    <autor></autor>
    <estacion>30</estacion>
    <publicado>1</publicado>
    <necesidades>8</necesidades>
    <localidad></localidad>
    <tipo_comida>8</tipo_comida>
    <almidon>3,9000000954</almidon>
    <grasa_total>43,5</grasa_total>
    <ags>17</ags>
    <agm>11,1000003815</agm>
    <agp>12,8000001907</agp>
    <agp_div_ags>0,75</agp_div_ags>
    <agp_mas_agm_div_ags>1,4099999666</agp_mas_agm_div_ags>
    <agua>144</agua>
    <alcohol>0</alcohol>
    <calcio>198</calcio>
    <hierro>1,7999999523</hierro>
    <yodo>15</yodo>
    <magnesio>67,0999984741</magnesio>
    <zinc>3,0999999046</zinc>
    <selenio>18,1000003815</selenio>
    <sodio>352</sodio>
    <potasio>487</potasio>
    <fosforo>782</fosforo>
    <fluor>184</fluor>
    <vitamina_b1>0,1599999964</vitamina_b1>
    <vitamina_b2>0,3400000036</vitamina_b2>
    <niacina>5,9000000954</niacina>
    <ac_pantotenico>0,75</ac_pantotenico>
    <vitamina_b6>0,3400000036</vitamina_b6>
    <acido_folico>49,5</acido_folico>
    <vitamina_b12>1</vitamina_b12>
    <biotina>8</biotina>
    <vitamina_c>10,1999998093</vitamina_c>
    <vitamina_a>401</vitamina_a>
    <retinol>308</retinol>
    <carotenos>27,7000007629</carotenos>
    <vitamina_d>0,0900000036</vitamina_d>
    <vitamina_e>2,2999999523</vitamina_e>
    <vitamina_k>4,5999999046</vitamina_k>
    <omega_3>2,4000000954</omega_3>
    <omega_6>10,1999998093</omega_6>
    <omega_3_div_6>0,2399999946</omega_3_div_6>
    <cafeina>0</cafeina>
    <teobromina>0</teobromina>
    <azucares_simples>48,5</azucares_simples>
    <fitoesteroles>27</fitoesteroles>
    <beta_sitosterol>21,7999992371</beta_sitosterol>
    <campesterol>1,5</campesterol>
    <estigmasterol>0</estigmasterol>
    <estigmaesterol_d7>0</estigmaesterol_d7>
    <brasica_esterol>0</brasica_esterol>
    <avenaesterol_d5>0</avenaesterol_d5>
    <avenaesterol_d7>0</avenaesterol_d7>
    <quercitina>0</quercitina>
    <quitar_medicos></quitar_medicos>
    <lleva_guarnicion></lleva_guarnicion>
    <trial445>T</trial445>
  </DATA_RECORD>
  <DATA_RECORD>
    <nombre>S/C</nombre>
    <id>57</id>
    <descripcion>Tostada de queso feta y aceitunas</descripcion>
    <comensales>4</comensales>
    <id_platip>0</id_platip>
    <id_tipprep>1</id_tipprep>
    <energia>245</energia>
    <carbohidratos>11,6999998093</carbohidratos>
    <proteinas>6,8000001907</proteinas>
    <grasas>18,7999992371</grasas>
    <estado>1</estado>
    <essimple>0</essimple>
    <fecha_publi>2013-04-25 00:00:00</fecha_publi>
    <descripcion_publi></descripcion_publi>
    <descripcion_v>Torrada de formatge feta i olives</descripcion_v>
    <descripcion_publi_v>Perquè no et calfes el cap cada dia a l'hora de cuinar, et proposem receptes pràctiques i senzilles per a dur una dieta sana i equilibrada, siga quin siga el teu estil de vida. Disfruta-les!</descripcion_publi_v>
    <url_amigable>tostada-de-queso-feta-y-aceitunas</url_amigable>
    <fibra>2,2000000477</fibra>
    <colesterol>26,7000007629</colesterol>
    <ingrediente_principal>24</ingrediente_principal>
    <perfil>181</perfil>
    <tipo_plato>2</tipo_plato>
    <basico>0</basico>
    <contenido>Trocear las aceitunas y el queso. Lavar el calabacín y cortarlo en tiras finas. Pelar la cebolla y trocearla.</contenido>
    <contenido_v>Trossegeu les olives i el formatge. Llaveu la carabasseta i talleu-la en tires fines. Peleu la ceba i trossegeu-la.</contenido_v>
    <autor></autor>
    <estacion>14</estacion>
    <publicado>1</publicado>
    <necesidades>14</necesidades>
    <localidad></localidad>
    <tipo_comida>1</tipo_comida>
    <almidon>8,6000003815</almidon>
    <grasa_total>18,7999992371</grasa_total>
    <ags>5,9000000954</ags>
    <agm>9,8000001907</agm>
    <agp>1,6000000238</agp>
    <agp_div_ags>0,2700000107</agp_div_ags>
    <agp_mas_agm_div_ags>1,9299999475</agp_mas_agm_div_ags>
    <agua>87,8000030518</agua>
    <alcohol>0</alcohol>
    <calcio>183</calcio>
    <hierro>2,0999999046</hierro>
    <yodo>3,9000000954</yodo>
    <magnesio>18</magnesio>
    <zinc>1,2000000477</zinc>
    <selenio>9,6000003815</selenio>
    <sodio>453</sodio>
    <potasio>202</potasio>
    <fosforo>145</fosforo>
    <fluor>0,4199999869</fluor>
    <vitamina_b1>0,1299999952</vitamina_b1>
    <vitamina_b2>0,3100000024</vitamina_b2>
    <niacina>1,2999999523</niacina>
    <ac_pantotenico>0,4300000072</ac_pantotenico>
    <vitamina_b6>0,200000003</vitamina_b6>
    <acido_folico>32,0999984741</acido_folico>
    <vitamina_b12>0,5099999905</vitamina_b12>
    <biotina>0,9499999881</biotina>
    <vitamina_c>8,8000001907</vitamina_c>
    <vitamina_a>61,5999984741</vitamina_a>
    <retinol>37,5</retinol>
    <carotenos>128</carotenos>
    <vitamina_d>0,1199999973</vitamina_d>
    <vitamina_e>1,5</vitamina_e>
    <vitamina_k>8,1000003815</vitamina_k>
    <omega_3>0,150000006</omega_3>
    <omega_6>1,2999999523</omega_6>
    <omega_3_div_6>0,1199999973</omega_3_div_6>
    <cafeina>0</cafeina>
    <teobromina>0</teobromina>
    <azucares_simples>3,0999999046</azucares_simples>
    <fitoesteroles>4,0999999046</fitoesteroles>
    <beta_sitosterol>2,7000000477</beta_sitosterol>
    <campesterol>0,2300000042</campesterol>
    <estigmasterol>0</estigmasterol>
    <estigmaesterol_d7>0</estigmaesterol_d7>
    <brasica_esterol>0</brasica_esterol>
    <avenaesterol_d5>0</avenaesterol_d5>
    <avenaesterol_d7>0</avenaesterol_d7>
    <quercitina>0</quercitina>
    <quitar_medicos></quitar_medicos>
    <lleva_guarnicion></lleva_guarnicion>
    <trial445>T</trial445>
  </DATA_RECORD>
  <DATA_RECORD>
    <nombre>S/C</nombre>
    <id>64</id>
    <descripcion>Pan de cereales con tofu y rodajas de tomate</descripcion>
    <comensales>4</comensales>
    <id_platip>0</id_platip>
    <id_tipprep>1</id_tipprep>
    <energia>258</energia>
    <carbohidratos>33,7000007629</carbohidratos>
    <proteinas>8,8999996185</proteinas>
    <grasas>8,3000001907</grasas>
    <estado>1</estado>
    <essimple>0</essimple>
    <fecha_publi>2013-05-03 00:00:00</fecha_publi>
    <descripcion_publi></descripcion_publi>
    <descripcion_v>Pa de cereals amb tofu i rodanxes de tomata</descripcion_v>
    <descripcion_publi_v>Perquè no et calfes el cap cada dia a l'hora de cuinar, et proposem receptes pràctiques i senzilles per a dur una dieta sana i equilibrada, siga quin siga el teu estil de vida. Disfruta-les!</descripcion_publi_v>
    <url_amigable>pan-de-cereales-con-tofu-y-rodajas-de-tomate</url_amigable>
    <fibra>6,1999998093</fibra>
    <colesterol>0</colesterol>
    <ingrediente_principal>38</ingrediente_principal>
    <perfil>223</perfil>
    <tipo_plato>128</tipo_plato>
    <basico>0</basico>
    <contenido>Cortar el tofu en rodajas finas.  Quitar el tallo de la cebolla y picarla.</contenido>
    <contenido_v>Talleu el tofu en rodanxes fines. Lleveu la tija de la ceba i piqueu-la.</contenido_v>
    <autor></autor>
    <estacion>30</estacion>
    <publicado>1</publicado>
    <necesidades>46</necesidades>
    <localidad></localidad>
    <tipo_comida>1</tipo_comida>
    <almidon>25,2999992371</almidon>
    <grasa_total>8,3000001907</grasa_total>
    <ags>1,2000000477</ags>
    <agm>4,1999998093</agm>
    <agp>2,2999999523</agp>
    <agp_div_ags>1,9199999571</agp_div_ags>
    <agp_mas_agm_div_ags>5,4200000763</agp_mas_agm_div_ags>
    <agua>164</agua>
    <alcohol>0</alcohol>
    <calcio>96,6999969482</calcio>
    <hierro>4,4000000954</hierro>
    <yodo>10,1999998093</yodo>
    <magnesio>81,1999969482</magnesio>
    <zinc>1,5</zinc>
    <selenio>24</selenio>
    <sodio>323</sodio>
    <potasio>440</potasio>
    <fosforo>151</fosforo>
    <fluor>9,6000003815</fluor>
    <vitamina_b1>0,2099999934</vitamina_b1>
    <vitamina_b2>0,1299999952</vitamina_b2>
    <niacina>3,9000000954</niacina>
    <ac_pantotenico>0,5500000119</ac_pantotenico>
    <vitamina_b6>0,2300000042</vitamina_b6>
    <acido_folico>43,2000007629</acido_folico>
    <vitamina_b12>0</vitamina_b12>
    <biotina>2,2999999523</biotina>
    <vitamina_c>21,7999992371</vitamina_c>
    <vitamina_a>163</vitamina_a>
    <retinol>0</retinol>
    <carotenos>972</carotenos>
    <vitamina_d>0</vitamina_d>
    <vitamina_e>2,7999999523</vitamina_e>
    <vitamina_k>16,2999992371</vitamina_k>
    <omega_3>0,2899999917</omega_3>
    <omega_6>2</omega_6>
    <omega_3_div_6>0,150000006</omega_3_div_6>
    <cafeina>0</cafeina>
    <teobromina>0</teobromina>
    <azucares_simples>8,3000001907</azucares_simples>
    <fitoesteroles>12,8999996185</fitoesteroles>
    <beta_sitosterol>6,1999998093</beta_sitosterol>
    <campesterol>1</campesterol>
    <estigmasterol>2,5</estigmasterol>
    <estigmaesterol_d7>0</estigmaesterol_d7>
    <brasica_esterol>0</brasica_esterol>
    <avenaesterol_d5>0</avenaesterol_d5>
    <avenaesterol_d7>0</avenaesterol_d7>
    <quercitina>0</quercitina>
    <quitar_medicos></quitar_medicos>
    <lleva_guarnicion></lleva_guarnicion>
    <trial445>T</trial445>
  </DATA_RECORD>
  <DATA_RECORD>
    <nombre>S/C</nombre>
    <id>67</id>
    <descripcion>Tostas de requesón y anchoas</descripcion>
    <comensales>4</comensales>
    <id_platip>0</id_platip>
    <id_tipprep></id_tipprep>
    <energia>138</energia>
    <carbohidratos>15,1000003815</carbohidratos>
    <proteinas>10,1999998093</proteinas>
    <grasas>3,7999999523</grasas>
    <estado>1</estado>
    <essimple>0</essimple>
    <fecha_publi>2013-05-03 00:00:00</fecha_publi>
    <descripcion_publi></descripcion_publi>
    <descripcion_v>Torrades de brull i anxoves</descripcion_v>
    <descripcion_publi_v>&amp;lt;p&amp;gt;Perquè no et calfes el cap cada dia a l'hora de cuinar, et proposem receptes pràctiques i senzilles per a dur una dieta sana i equilibrada, siga quin siga el teu estil de vida. Disfruta-les!&amp;lt;/p&amp;gt;</descripcion_publi_v>
    <url_amigable>tostas-de-requeson-y-anchoas</url_amigable>
    <fibra>1,2999999523</fibra>
    <colesterol>12</colesterol>
    <ingrediente_principal>24</ingrediente_principal>
    <perfil>220</perfil>
    <tipo_plato>2</tipo_plato>
    <basico>0</basico>
    <contenido>Mezclar el requesón, las anchoas, el rábano y la mostaza, hasta conseguir una pasta homogénea. Pelar la cebolla y picarla muy fina. Añadirla al puré anterior. Salpimentar al gusto.</contenido>
    <contenido_v>Mescleu el brull, les anxoves, el rave i la mostassa, fins a aconseguir una pasta homogènia. Peleu la ceba i piqueu-la molt fina. Afegiu-la al puré anterior. Salpebreu-ho al gust.</contenido_v>
    <autor></autor>
    <estacion>30</estacion>
    <publicado>1</publicado>
    <necesidades>6</necesidades>
    <localidad></localidad>
    <tipo_comida>1</tipo_comida>
    <almidon>12</almidon>
    <grasa_total>3,7999999523</grasa_total>
    <ags>1,5</ags>
    <agm>1,1000000238</agm>
    <agp>0,5799999833</agp>